language: node_js

node_js:
  - "0.11"
  - "0.10"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g grunt-cli

env:
  global:
    - secure: HO29nd5C/1QehlGIOk1pWo//HrfBKitsjEsbGykheNYg/3tyWH7bbSBSkA+4laUJADg4JD13ECsUZC1pydcBb9SFJ04SrZgh+XJpqRSBBQS/rneOXRr9EDGSoYi3V8YeBgHMIiGnCuSW1PhVko/EElxe4tjNGkE3Uhx8vPCO27Q=
    - secure: i/tkgiAh57JonmCTYHkV1bxWwa3vfYqmYEDr4d6gO/g+abwKgHCIWigcJ8VKKl+ebAHv40WrxPGPxmG7ROADroiS6t826R6TLHqAiSD8Eq8HjaetTndVmUtNI7wzR4tEffBj5ZttF1voB1ej2gDouqZ5PAp3wmShg/jXkzEkGm8=

addons:
  sauce_connect: true
